
TRAIN:
  TYPE: "train_parameters"
  PROJECT_NAME: 'Syn2Sp_M34_SelfTraining'
  
  # for transfer learning
  MAX_ITERS: 100000
  MAX_EPOCHS: 100000

  PREHEAT_STEPS: 5000
  T_VAL_ITER: 1000
  S_VAL_ITER: 4000
  SAVE_MORE_ITER: False
  SAVE_ITER: 80000
  LOG_PERIOD: 50
  PRETRAINPATH: 'preTraModel/Syn2Sp/SynLiDAR2SP_M34_XYZ/2022-10-27-08_58/checkpoint_epoch_10.tar'
  RESUMEPATH: None
  
  EXP_NAME: "2P_SoftDice_noSchelur_1Mt9e2_CosMix_10Ch_CE_M34_SGD1e3_ym" # 
  STAGE: "CoSMix_Trainer"
  GPU_ID: 2
  DEBUG: False # False | True 
  
  use_softdice: True  # _softdice

# keep the setting with cosmix-uda-main/configs/adaptation/synlidar2semantickitti_cosmix.yaml

SOURCE_LOSS:
  lambda_lov: 0. 

TARGET_LOSS:

MEAN_TEACHER:
  TYPE: 'meanTeacher'
  use_mt: True # Mt9e3 == 0.999
  alpha_ema: 0.99
  update_every: 1 # 0000000

HYPERPARAMETER:
  VOXEL_SIZE: 0.05

#------ Network ------
MODEL_G:
  TYPE: "G"
  MODEL_NAME: "MinkUNet34"
  IN_CHANNELS: 3  # coords (xyz) and intensity
  NUM_CLASSES: 14  # Number of valid classes

PSEUDO_LABEL:
  use_confidence: True # True | False #
  threshold: 0.9
  
OPTIMIZER:
  TYPE: "SGD"
  LEARNING_RATE_G: 1.e-3 # max learning rate of G

#------ dataset ------
DATASET_SOURCE:
  TYPE: "SynLiDAR"
  d_domain: 'source'

  CoSMix_sampling_weights: [0.0,                0.9871745850290106, 0.9638883391233276, 0.9903653951801328,
                            0.8013865034691628, 0.9981232577847288, 0.9896608393217328, 0.9951673782429917,
                            0.805815652852364,  0.9994948429821191, 0.9709256189795944, 0.9961168040207042,
                            0.5093477564672759, 0.9925330265468555]

  data_config_file: 'dataset/configs/SynLiDAR2SemanticPOSS/annotations.yaml'
  class_mapping: "map_2_semanticposs"
  class_mapping_labels: "map_2_semanticposs_labels"

  train_seq_list: ['00', '01', '02', '03', '04', '05', '06',
                   '07', '08', '09', '10', '11', '12']
  
  valid_seq_list: ['03']

  USE_INTENSITY: False # 输入是否使用Intensity
  
  VOXEL_SIZE: 0.05
  IN_NUM_VOXELS: -1000 # 70000

  DATASET_DIR: '~/dataset/SynLiDAR/sub_dataset'
  


  
  
DATASET_TARGET:
  TYPE: "SemanticPOSS"
  d_domain: 'target'

  data_config_file: 'dataset/configs/SynLiDAR2SemanticPOSS/semantic-poss.yaml'
  class_mapping: 'learning_map' 
  class_mapping_labels: "labels"

  train_seq_list: ['00', '01', '02', '05', '04']
  
  valid_seq_list: ['03']

  USE_INTENSITY: False

  VOXEL_SIZE: 0.05
  IN_NUM_VOXELS: -80000

  DATASET_DIR: '~/dataset/semanticPOSS/dataset/sequences/'
  
DATALOADER:
  NUM_WORKERS: 2
  TRA_BATCH_SIZE: 2
  VAL_BATCH_SIZE: 4

DEBUG:
  T_VAL_ITER: 5
  S_VAL_ITER: 20
  LOG_PERIOD: 1
  PREHEAT_STEPS: 10
  EXP_NAME: 'debug'
  PROTO_UPDATE_PERIOD: 15
  T_THRE_ZERO_ITER: 13
  AUX_LOSS_START_ITER: 12

